/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "MaquinaEstado.v:1" *)
module MaquinaEstado(CLK, RESET, Tarjeta_Recibida, Tipo_Trans, Digito_STB, Digito, PIN, Monto_STB, Monto, BALANCE, Balance_Actualizado, Entregar_Dinero, Pin_Incorrecto, Advertencia, Bloqueo, Fondos_Insuficientes);
  (* src = "MaquinaEstado.v:54" *)
  wire _000_;
  (* src = "MaquinaEstado.v:54" *)
  wire _001_;
  (* src = "MaquinaEstado.v:54" *)
  wire _002_;
  (* src = "MaquinaEstado.v:54" *)
  wire [1:0] _003_;
  (* src = "MaquinaEstado.v:54" *)
  wire [2:0] _004_;
  (* src = "MaquinaEstado.v:54" *)
  wire [2:0] _005_;
  (* src = "MaquinaEstado.v:54" *)
  wire [63:0] _006_;
  (* src = "MaquinaEstado.v:54" *)
  wire [1:0] _007_;
  (* src = "MaquinaEstado.v:54" *)
  wire _008_;
  (* src = "MaquinaEstado.v:54" *)
  wire _009_;
  (* src = "MaquinaEstado.v:54" *)
  wire _010_;
  (* src = "MaquinaEstado.v:54" *)
  wire [1:0] _011_;
  (* src = "MaquinaEstado.v:54" *)
  wire [1:0] _012_;
  (* src = "MaquinaEstado.v:54" *)
  wire [2:0] _013_;
  (* src = "MaquinaEstado.v:54" *)
  wire [2:0] _014_;
  (* src = "MaquinaEstado.v:108" *)
  (* unused_bits = "2" *)
  wire [31:0] _015_;
  wire _016_;
  wire [31:0] _017_;
  wire [15:0] _018_;
  wire [7:0] _019_;
  wire [3:0] _020_;
  wire [1:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [1:0] _031_;
  wire [63:0] _032_;
  wire [2:0] _033_;
  wire [2:0] _034_;
  wire [2:0] _035_;
  wire [2:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [1:0] _045_;
  wire [1:0] _046_;
  (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:432" *)
  wire [8:0] _047_;
  (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:428" *)
  wire [2:0] _048_;
  wire [2:0] _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [1:0] _054_;
  wire _055_;
  (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:432" *)
  wire [1:0] _056_;
  (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:428" *)
  wire _057_;
  wire _058_;
  (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *)
  wire _059_;
  (* src = "MaquinaEstado.v:15" *)
  output Advertencia;
  (* src = "MaquinaEstado.v:11" *)
  output [63:0] BALANCE;
  (* init = 1'h0 *)
  (* src = "MaquinaEstado.v:12" *)
  output Balance_Actualizado;
  (* init = 1'h0 *)
  (* src = "MaquinaEstado.v:16" *)
  output Bloqueo;
  (* src = "MaquinaEstado.v:2" *)
  input CLK;
  (* src = "MaquinaEstado.v:7" *)
  input [3:0] Digito;
  (* src = "MaquinaEstado.v:6" *)
  input Digito_STB;
  (* init = 1'h0 *)
  (* src = "MaquinaEstado.v:13" *)
  output Entregar_Dinero;
  (* init = 2'h0 *)
  (* src = "MaquinaEstado.v:17" *)
  output [1:0] Fondos_Insuficientes;
  (* src = "MaquinaEstado.v:22" *)
  wire Intento_incorrecto;
  (* src = "MaquinaEstado.v:10" *)
  input [31:0] Monto;
  (* src = "MaquinaEstado.v:9" *)
  input Monto_STB;
  (* src = "MaquinaEstado.v:8" *)
  input [15:0] PIN;
  (* src = "MaquinaEstado.v:14" *)
  output Pin_Incorrecto;
  (* src = "MaquinaEstado.v:27" *)
  wire [1:0] Prox_pin_attempt;
  (* src = "MaquinaEstado.v:3" *)
  input RESET;
  (* src = "MaquinaEstado.v:4" *)
  input Tarjeta_Recibida;
  (* src = "MaquinaEstado.v:5" *)
  input Tipo_Trans;
  (* src = "MaquinaEstado.v:23" *)
  wire [63:0] prox_balance;
  (* src = "MaquinaEstado.v:40" *)
  wire [2:0] proximo_estado;
  assign _037_ = _031_[0] |(* src = "MaquinaEstado.v:109" *)  _031_[1];
  assign _016_ = _051_ | _050_;
  assign _017_[0] = _032_[0] |(* src = "MaquinaEstado.v:121" *)  _032_[1];
  assign _017_[1] = _032_[2] |(* src = "MaquinaEstado.v:121" *)  _032_[3];
  assign _017_[2] = _032_[4] |(* src = "MaquinaEstado.v:121" *)  _032_[5];
  assign _017_[3] = _032_[6] |(* src = "MaquinaEstado.v:121" *)  _032_[7];
  assign _017_[4] = _032_[8] |(* src = "MaquinaEstado.v:121" *)  _032_[9];
  assign _017_[5] = _032_[10] |(* src = "MaquinaEstado.v:121" *)  _032_[11];
  assign _017_[6] = _032_[12] |(* src = "MaquinaEstado.v:121" *)  _032_[13];
  assign _017_[7] = _032_[14] |(* src = "MaquinaEstado.v:121" *)  _032_[15];
  assign _017_[8] = _032_[16] |(* src = "MaquinaEstado.v:121" *)  _032_[17];
  assign _017_[9] = _032_[18] |(* src = "MaquinaEstado.v:121" *)  _032_[19];
  assign _017_[10] = _032_[20] |(* src = "MaquinaEstado.v:121" *)  _032_[21];
  assign _017_[11] = _032_[22] |(* src = "MaquinaEstado.v:121" *)  _032_[23];
  assign _017_[12] = _032_[24] |(* src = "MaquinaEstado.v:121" *)  _032_[25];
  assign _017_[13] = _032_[26] |(* src = "MaquinaEstado.v:121" *)  _032_[27];
  assign _017_[14] = _032_[28] |(* src = "MaquinaEstado.v:121" *)  _032_[29];
  assign _017_[15] = _032_[30] |(* src = "MaquinaEstado.v:121" *)  _032_[31];
  assign _017_[16] = _006_[32] |(* src = "MaquinaEstado.v:121" *)  _006_[33];
  assign _017_[17] = _006_[34] |(* src = "MaquinaEstado.v:121" *)  _006_[35];
  assign _017_[18] = _006_[36] |(* src = "MaquinaEstado.v:121" *)  _006_[37];
  assign _017_[19] = _006_[38] |(* src = "MaquinaEstado.v:121" *)  _006_[39];
  assign _017_[20] = _006_[40] |(* src = "MaquinaEstado.v:121" *)  _006_[41];
  assign _017_[21] = _006_[42] |(* src = "MaquinaEstado.v:121" *)  _006_[43];
  assign _017_[22] = _006_[44] |(* src = "MaquinaEstado.v:121" *)  _006_[45];
  assign _017_[23] = _006_[46] |(* src = "MaquinaEstado.v:121" *)  _006_[47];
  assign _017_[24] = _006_[48] |(* src = "MaquinaEstado.v:121" *)  _006_[49];
  assign _017_[25] = _006_[50] |(* src = "MaquinaEstado.v:121" *)  _006_[51];
  assign _017_[26] = _006_[52] |(* src = "MaquinaEstado.v:121" *)  _006_[53];
  assign _017_[27] = _006_[54] |(* src = "MaquinaEstado.v:121" *)  _006_[55];
  assign _017_[28] = _006_[56] |(* src = "MaquinaEstado.v:121" *)  _006_[57];
  assign _017_[29] = _006_[58] |(* src = "MaquinaEstado.v:121" *)  _006_[59];
  assign _017_[30] = _006_[60] |(* src = "MaquinaEstado.v:121" *)  _006_[61];
  assign _017_[31] = _006_[62] |(* src = "MaquinaEstado.v:121" *)  _006_[63];
  assign _018_[0] = _017_[0] |(* src = "MaquinaEstado.v:121" *)  _017_[1];
  assign _018_[1] = _017_[2] |(* src = "MaquinaEstado.v:121" *)  _017_[3];
  assign _018_[2] = _017_[4] |(* src = "MaquinaEstado.v:121" *)  _017_[5];
  assign _018_[3] = _017_[6] |(* src = "MaquinaEstado.v:121" *)  _017_[7];
  assign _018_[4] = _017_[8] |(* src = "MaquinaEstado.v:121" *)  _017_[9];
  assign _018_[5] = _017_[10] |(* src = "MaquinaEstado.v:121" *)  _017_[11];
  assign _018_[6] = _017_[12] |(* src = "MaquinaEstado.v:121" *)  _017_[13];
  assign _018_[7] = _017_[14] |(* src = "MaquinaEstado.v:121" *)  _017_[15];
  assign _018_[8] = _017_[16] |(* src = "MaquinaEstado.v:121" *)  _017_[17];
  assign _018_[9] = _017_[18] |(* src = "MaquinaEstado.v:121" *)  _017_[19];
  assign _018_[10] = _017_[20] |(* src = "MaquinaEstado.v:121" *)  _017_[21];
  assign _018_[11] = _017_[22] |(* src = "MaquinaEstado.v:121" *)  _017_[23];
  assign _018_[12] = _017_[24] |(* src = "MaquinaEstado.v:121" *)  _017_[25];
  assign _018_[13] = _017_[26] |(* src = "MaquinaEstado.v:121" *)  _017_[27];
  assign _018_[14] = _017_[28] |(* src = "MaquinaEstado.v:121" *)  _017_[29];
  assign _018_[15] = _017_[30] |(* src = "MaquinaEstado.v:121" *)  _017_[31];
  assign _019_[0] = _018_[0] |(* src = "MaquinaEstado.v:121" *)  _018_[1];
  assign _019_[1] = _018_[2] |(* src = "MaquinaEstado.v:121" *)  _018_[3];
  assign _019_[2] = _018_[4] |(* src = "MaquinaEstado.v:121" *)  _018_[5];
  assign _019_[3] = _018_[6] |(* src = "MaquinaEstado.v:121" *)  _018_[7];
  assign _019_[4] = _018_[8] |(* src = "MaquinaEstado.v:121" *)  _018_[9];
  assign _019_[5] = _018_[10] |(* src = "MaquinaEstado.v:121" *)  _018_[11];
  assign _019_[6] = _018_[12] |(* src = "MaquinaEstado.v:121" *)  _018_[13];
  assign _019_[7] = _018_[14] |(* src = "MaquinaEstado.v:121" *)  _018_[15];
  assign _020_[0] = _019_[0] |(* src = "MaquinaEstado.v:121" *)  _019_[1];
  assign _020_[1] = _019_[2] |(* src = "MaquinaEstado.v:121" *)  _019_[3];
  assign _020_[2] = _019_[4] |(* src = "MaquinaEstado.v:121" *)  _019_[5];
  assign _020_[3] = _019_[6] |(* src = "MaquinaEstado.v:121" *)  _019_[7];
  assign _021_[0] = _020_[0] |(* src = "MaquinaEstado.v:121" *)  _020_[1];
  assign _021_[1] = _020_[2] |(* src = "MaquinaEstado.v:121" *)  _020_[3];
  assign _038_ = _021_[0] |(* src = "MaquinaEstado.v:121" *)  _021_[1];
  assign _022_ = _004_[0] |(* src = "MaquinaEstado.v:113|MaquinaEstado.v:86" *)  _033_[1];
  assign _039_ = _022_ |(* src = "MaquinaEstado.v:113|MaquinaEstado.v:86" *)  _004_[2];
  assign _023_ = _034_[0] |(* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *)  _004_[1];
  assign _040_ = _023_ |(* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *)  _004_[2];
  assign _024_ = _004_[0] |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86" *)  _004_[1];
  assign _041_ = _024_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86" *)  _035_[2];
  assign _025_ = _034_[0] |(* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *)  _033_[1];
  assign _042_ = _025_ |(* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *)  _004_[2];
  assign _026_ = _036_[0] |(* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *)  _004_[1];
  assign _043_ = _026_ |(* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *)  _004_[2];
  assign _027_ = _047_[2] |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[5];
  assign _048_[2] = _027_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[8];
  assign _028_ = _047_[1] |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[4];
  assign _048_[1] = _028_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[7];
  assign _029_ = _047_[0] |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[4];
  assign _048_[0] = _029_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _047_[6];
  assign _030_ = _016_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *)  _052_;
  assign _059_ = _030_ |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *)  _044_;
  assign _057_ = _056_[0] |(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:441" *)  _056_[1];
  assign _052_ = ~(* src = "MaquinaEstado.v:113|MaquinaEstado.v:86" *) _039_;
  assign _044_ = ~(* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *) _040_;
  assign _050_ = ~(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86" *) _041_;
  assign _051_ = ~(* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *) _042_;
  assign _010_ = _038_ ? (* src = "MaquinaEstado.v:121" *) Entregar_Dinero : 1'h1;
  assign _008_ = _038_ ? (* src = "MaquinaEstado.v:121" *) Balance_Actualizado : 1'h1;
  assign _011_[0] = _038_ ? (* src = "MaquinaEstado.v:121" *) 1'h1 : Fondos_Insuficientes[0];
  assign _011_[1] = _038_ ? (* src = "MaquinaEstado.v:121" *) 1'h0 : Fondos_Insuficientes[1];
  assign _014_[2] = ~(* src = "MaquinaEstado.v:114" *) Tipo_Trans;
  assign _009_ = _037_ ? (* src = "MaquinaEstado.v:109" *) Bloqueo : 1'h1;
  assign _013_[0] = Digito_STB ? (* src = "MaquinaEstado.v:103" *) 1'h0 : proximo_estado[0];
  assign _013_[1] = Digito_STB ? (* src = "MaquinaEstado.v:103" *) 1'h1 : proximo_estado[1];
  assign _013_[2] = Digito_STB ? (* src = "MaquinaEstado.v:103" *) 1'h0 : proximo_estado[2];
  assign _045_[0] = Digito_STB ? (* src = "MaquinaEstado.v:103" *) _007_[0] : _015_[0];
  assign _045_[1] = Digito_STB ? (* src = "MaquinaEstado.v:103" *) _007_[1] : _015_[1];
  assign _046_[0] = _040_ ? (* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *) 1'hx : _045_[0];
  assign _046_[1] = _040_ ? (* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *) 1'hx : _045_[1];
  assign _012_[0] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _046_[0] : 1'hx;
  assign _012_[1] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _046_[1] : 1'hx;
  assign _005_[0] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _049_[0] : Tarjeta_Recibida;
  assign _005_[1] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _049_[1] : 1'h0;
  assign _005_[2] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _049_[2] : 1'h0;
  assign _053_ = _040_ ? (* src = "MaquinaEstado.v:102|MaquinaEstado.v:86" *) Bloqueo : _009_;
  assign _001_ = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _053_ : 1'h0;
  assign _054_[0] = _042_ ? (* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *) Fondos_Insuficientes[0] : _011_[0];
  assign _054_[1] = _042_ ? (* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *) Fondos_Insuficientes[1] : _011_[1];
  assign _003_[0] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _054_[0] : 1'h0;
  assign _003_[1] = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _054_[1] : 1'h0;
  assign _055_ = _042_ ? (* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *) Entregar_Dinero : _010_;
  assign _002_ = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _055_ : 1'h0;
  assign _000_ = _043_ ? (* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *) _058_ : Balance_Actualizado;
  assign _007_[0] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : Prox_pin_attempt[0];
  assign _007_[1] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : Prox_pin_attempt[1];
  assign _006_[0] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[0];
  assign _006_[1] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[1];
  assign _006_[2] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[2];
  assign _006_[3] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[3];
  assign _006_[4] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[4];
  assign _006_[5] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[5];
  assign _006_[6] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[6];
  assign _006_[7] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[7];
  assign _006_[8] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[8];
  assign _006_[9] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[9];
  assign _006_[10] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[10];
  assign _006_[11] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[11];
  assign _006_[12] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[12];
  assign _006_[13] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[13];
  assign _006_[14] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[14];
  assign _006_[15] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[15];
  assign _006_[16] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[16];
  assign _006_[17] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[17];
  assign _006_[18] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[18];
  assign _006_[19] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[19];
  assign _006_[20] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[20];
  assign _006_[21] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[21];
  assign _006_[22] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[22];
  assign _006_[23] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[23];
  assign _006_[24] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[24];
  assign _006_[25] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[25];
  assign _006_[26] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[26];
  assign _006_[27] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h1 : prox_balance[27];
  assign _006_[28] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[28];
  assign _006_[29] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[29];
  assign _006_[30] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[30];
  assign _006_[31] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[31];
  assign _006_[32] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[32];
  assign _006_[33] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[33];
  assign _006_[34] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[34];
  assign _006_[35] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[35];
  assign _006_[36] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[36];
  assign _006_[37] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[37];
  assign _006_[38] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[38];
  assign _006_[39] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[39];
  assign _006_[40] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[40];
  assign _006_[41] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[41];
  assign _006_[42] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[42];
  assign _006_[43] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[43];
  assign _006_[44] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[44];
  assign _006_[45] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[45];
  assign _006_[46] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[46];
  assign _006_[47] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[47];
  assign _006_[48] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[48];
  assign _006_[49] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[49];
  assign _006_[50] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[50];
  assign _006_[51] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[51];
  assign _006_[52] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[52];
  assign _006_[53] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[53];
  assign _006_[54] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[54];
  assign _006_[55] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[55];
  assign _006_[56] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[56];
  assign _006_[57] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[57];
  assign _006_[58] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[58];
  assign _006_[59] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[59];
  assign _006_[60] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[60];
  assign _006_[61] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[61];
  assign _006_[62] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[62];
  assign _006_[63] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : prox_balance[63];
  assign _004_[0] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : proximo_estado[0];
  assign _004_[1] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : proximo_estado[1];
  assign _004_[2] = RESET ? (* src = "MaquinaEstado.v:55" *) 1'h0 : proximo_estado[2];
  assign _049_[0] = _059_ ? (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *) _048_[0] : 1'h0;
  assign _049_[1] = _059_ ? (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *) _048_[1] : 1'h0;
  assign _049_[2] = _059_ ? (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *) _048_[2] : 1'h0;
  assign _058_ = _016_ ? (* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:445" *) _057_ : Balance_Actualizado;
  (* src = "MaquinaEstado.v:54" *)
  DFF _248_ (
    .C(CLK),
    .D(_000_),
    .Q(Balance_Actualizado)
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _249_ (
    .C(CLK),
    .D(_002_),
    .Q(Entregar_Dinero)
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _250_ (
    .C(CLK),
    .D(_001_),
    .Q(Bloqueo)
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _251_ (
    .C(CLK),
    .D(_003_[0]),
    .Q(Fondos_Insuficientes[0])
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _252_ (
    .C(CLK),
    .D(_003_[1]),
    .Q(Fondos_Insuficientes[1])
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _253_ (
    .C(CLK),
    .D(_005_[0]),
    .Q(proximo_estado[0])
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _254_ (
    .C(CLK),
    .D(_005_[1]),
    .Q(proximo_estado[1])
  );
  (* src = "MaquinaEstado.v:54" *)
  DFF _255_ (
    .C(CLK),
    .D(_005_[2]),
    .Q(proximo_estado[2])
  );
  assign _031_[0] = _012_[0] ^(* src = "MaquinaEstado.v:109" *)  1'h1;
  assign _031_[1] = _012_[1] ^(* src = "MaquinaEstado.v:109" *)  1'h1;
  assign _032_[0] = Monto[0] ^(* src = "MaquinaEstado.v:121" *)  _006_[0];
  assign _032_[1] = Monto[1] ^(* src = "MaquinaEstado.v:121" *)  _006_[1];
  assign _032_[2] = Monto[2] ^(* src = "MaquinaEstado.v:121" *)  _006_[2];
  assign _032_[3] = Monto[3] ^(* src = "MaquinaEstado.v:121" *)  _006_[3];
  assign _032_[4] = Monto[4] ^(* src = "MaquinaEstado.v:121" *)  _006_[4];
  assign _032_[5] = Monto[5] ^(* src = "MaquinaEstado.v:121" *)  _006_[5];
  assign _032_[6] = Monto[6] ^(* src = "MaquinaEstado.v:121" *)  _006_[6];
  assign _032_[7] = Monto[7] ^(* src = "MaquinaEstado.v:121" *)  _006_[7];
  assign _032_[8] = Monto[8] ^(* src = "MaquinaEstado.v:121" *)  _006_[8];
  assign _032_[9] = Monto[9] ^(* src = "MaquinaEstado.v:121" *)  _006_[9];
  assign _032_[10] = Monto[10] ^(* src = "MaquinaEstado.v:121" *)  _006_[10];
  assign _032_[11] = Monto[11] ^(* src = "MaquinaEstado.v:121" *)  _006_[11];
  assign _032_[12] = Monto[12] ^(* src = "MaquinaEstado.v:121" *)  _006_[12];
  assign _032_[13] = Monto[13] ^(* src = "MaquinaEstado.v:121" *)  _006_[13];
  assign _032_[14] = Monto[14] ^(* src = "MaquinaEstado.v:121" *)  _006_[14];
  assign _032_[15] = Monto[15] ^(* src = "MaquinaEstado.v:121" *)  _006_[15];
  assign _032_[16] = Monto[16] ^(* src = "MaquinaEstado.v:121" *)  _006_[16];
  assign _032_[17] = Monto[17] ^(* src = "MaquinaEstado.v:121" *)  _006_[17];
  assign _032_[18] = Monto[18] ^(* src = "MaquinaEstado.v:121" *)  _006_[18];
  assign _032_[19] = Monto[19] ^(* src = "MaquinaEstado.v:121" *)  _006_[19];
  assign _032_[20] = Monto[20] ^(* src = "MaquinaEstado.v:121" *)  _006_[20];
  assign _032_[21] = Monto[21] ^(* src = "MaquinaEstado.v:121" *)  _006_[21];
  assign _032_[22] = Monto[22] ^(* src = "MaquinaEstado.v:121" *)  _006_[22];
  assign _032_[23] = Monto[23] ^(* src = "MaquinaEstado.v:121" *)  _006_[23];
  assign _032_[24] = Monto[24] ^(* src = "MaquinaEstado.v:121" *)  _006_[24];
  assign _032_[25] = Monto[25] ^(* src = "MaquinaEstado.v:121" *)  _006_[25];
  assign _032_[26] = Monto[26] ^(* src = "MaquinaEstado.v:121" *)  _006_[26];
  assign _032_[27] = Monto[27] ^(* src = "MaquinaEstado.v:121" *)  _006_[27];
  assign _032_[28] = Monto[28] ^(* src = "MaquinaEstado.v:121" *)  _006_[28];
  assign _032_[29] = Monto[29] ^(* src = "MaquinaEstado.v:121" *)  _006_[29];
  assign _032_[30] = Monto[30] ^(* src = "MaquinaEstado.v:121" *)  _006_[30];
  assign _032_[31] = Monto[31] ^(* src = "MaquinaEstado.v:121" *)  _006_[31];
  assign _035_[2] = _004_[2] ^(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86" *)  1'h1;
  assign _034_[0] = _004_[0] ^(* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *)  1'h1;
  assign _033_[1] = _004_[1] ^(* src = "MaquinaEstado.v:120|MaquinaEstado.v:86" *)  1'h1;
  assign _036_[0] = _004_[0] ^(* src = "MaquinaEstado.v:87|MaquinaEstado.v:86" *)  Tarjeta_Recibida;
  assign _047_[4] = Tipo_Trans &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _052_;
  assign _047_[5] = _014_[2] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _052_;
  assign _047_[6] = _013_[0] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _044_;
  assign _047_[7] = _013_[1] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _044_;
  assign _047_[8] = _013_[2] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _044_;
  assign _047_[0] = proximo_estado[0] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _016_;
  assign _047_[1] = proximo_estado[1] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _016_;
  assign _047_[2] = proximo_estado[2] &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _016_;
  assign _056_[0] = Monto_STB &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _050_;
  assign _056_[1] = _008_ &(* src = "MaquinaEstado.v:130|MaquinaEstado.v:86|<techmap.v>:434" *)  _051_;
  assign _015_[1] = _007_[1] ^(* src = "MaquinaEstado.v:108|<techmap.v>:263" *)  _007_[0];
  assign _015_[0] = _007_[0] ^(* src = "MaquinaEstado.v:108|<techmap.v>:262" *)  1'h1;
  assign _014_[1:0] = { Tipo_Trans, Tipo_Trans };
  assign _015_[31:3] = 29'h00000000;
  assign _032_[63:32] = _006_[63:32];
  assign { _033_[2], _033_[0] } = { _004_[2], _004_[0] };
  assign _034_[2:1] = _004_[2:1];
  assign _035_[1:0] = _004_[1:0];
  assign _036_[2:1] = _004_[2:1];
  assign _047_[3] = _047_[4];
  assign Advertencia = 1'h0;
  assign BALANCE = 64'h0000000000000000;
  assign Intento_incorrecto = 1'h0;
  assign Pin_Incorrecto = 1'h0;
endmodule
